### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by c0h1b4** [2d-inc/developer_quest#132]
Hello, I just cloned the repo and when compiling/running, I get this error:

```
Compiler message:
file:///Users/david/development/flutter/.pub-cache/git/Flare-Flutter-4aebb0ff5b98c7bcf2183c6bac8226cc7ddf5402/flare_flutter/lib/flare.dart:1023:18: Error: The argument type 'Int32List' can't be assigned to the parameter type 'Uint16List'.
 - 'Int32List' is from 'dart:typed_data'.
 - 'Uint16List' is from 'dart:typed_data'.
Try changing the type of the parameter, or casting the argument to 'Uint16List'.
        indices: _indices, textureCoordinates: _uvBuffer);
                 ^
Compiler failed on /Users/david/development/projects/developer_quest/lib/main.dart
Gradle task assembleDebug failed with exit code 1

```

This is my flutter doctor:

[✓] Flutter (Channel dev, v1.5.8, on Mac OS X 10.14.4 18E226, locale en-BR)
    • Flutter version 1.5.8 at /Users/david/development/flutter
    • Framework revision 0ba67226ee (2 weeks ago), 2019-04-24 17:18:28 -0700
    • Engine revision c63d1cf9c9
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 1f1592edce)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/david/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/david/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/david/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.0.beta.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.1

[✓] Connected device (2 available)
    • Redmi Go     • 106ad4f17d85 • android-arm   • Android 8.1.0 (API 27)
    • OnePlus 6    • 9dc80123     • android-arm64 • Android 9 (API 28)

• No issues found!

Any hints on what is breaking the project?

David

**Comment by c0h1b4** [comment]
Never mind. I got this. It is a flare issue.

https://github.com/2d-inc/Flare-Flutter/issues/75#issuecomment-491022299

**Comment by amorenew** [comment]
flare_flutter:
  git: 
    url: git://github.com/2d-inc/Flare-Flutter.git
    **ref: dev**
    path: flare_flutter
 solve it for me
