### ISSUE TITLE
Open Source Animations in Flare?

### ISSUE THREAD

**Issue by smholsen** [2d-inc/developer_quest#134]
Hi!
Thank you very much for an amazing repo and showcase of both Flutter and Flare. 

I am sorry if this is not the correct channel for this type of question, but I was not sure where to reach out to you. 
I wanted to ask if you would open source the source Flare file for the animations used in this project? I was inspired by this project to start work on a similar game, and it would be very educational and interesting to see how these amazing animations were made.

Thanks again.

**Comment by zenz** [comment]
some of them:
https://www.2dimensions.com/a/BlackHive/files/recent/all

**Comment by smholsen** [comment]
That is amazing, thank you 🔥
