### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [2d-inc/developer_quest#135]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by zenz** [comment]
Hi, @mansya. This project is under MIT License, so you can fork it and modify it. if it's good enough, you can make a pull request and ask for merge.

**Comment by mansya** [comment]
HI, sir, I have designed it. How ? do you like it ? if yes please tell me which one you like.
![Developer Quest](https://user-images.githubusercontent.com/33461607/59457902-8e212280-8e43-11e9-82de-7a84b869f795.png)

**Comment by mansya** [comment]
hi sir. how about this offer. don't you want to continue?
