### ISSUE TITLE
The argument type 'Uint16List' can't be assigned to the parameter type 'Int32List'

### ISSUE THREAD

**Issue by twovs** [2d-inc/developer_quest#143]
Compiler message:
file:///G:/flutter/.pub-cache/git/Flare-Flutter-307d63f824042d61059edf1cec54b96789625d97/flare_flutter/lib/flare.dart:1027:18: Error: The argument type 'Uint16List' can't be assigned to the parameter type 'Int32List'.
 - 'Uint16List' is from 'dart:typed_data'.
 - 'Int32List' is from 'dart:typed_data'.
Try changing the type of the parameter, or casting the argument to 'Int32List'.
        indices: _indices, textureCoordinates: _uvBuffer);
                 ^
Compiler failed on G:\flutterapps\twovv_programmer_english\lib\main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

G:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (**Channel stable, v1.5.4-hotfix.2, on** Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 1.5.4-hotfix.2 at G:\flutter
    • Framework revision 7a4c33425d (2 months ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at G:/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = G:/Android/Sdk
    • Java binary at: G:\Android_Studio_UP\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at G:\Android_Studio_UP
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (1 available)
    • oppo r9 plustm a • emulator-5554 • android-x86 • Android 5.1.1 (API 22)

• No issues found!
Process finished with exit code 0

**Comment by twovs** [comment]
flare_flutter:
    git:
      url: git://github.com/2d-inc/Flare-Flutter.git
      ref: dev
      path: flare_flutter

**Comment by twovs** [comment]
flare_flutter: ^1.5.4

**Comment by YouCii** [comment]
I solved the problem by changing flare_flutter's ref to dev. My Flutter version is 1.7.8+hotfix.3. 
Maybe you can try upgrade the flutter library.

**Comment by luigi-rosso** [comment]
If you see still see this message it's likely due to your flutter being out of date. 

```
flutter channel stable
flutter upgrade
```

Then make sure your pubspec is pointing to ^1.5.4. Flare 1.5.4 is only compatible with stable 1.7.8 and above.

**Comment by twovs** [comment]
nice, flare_flutter: ^1.5.4 need flutter stable 1.7.8+
