### ISSUE TITLE
it like a bug or version issue

### ISSUE THREAD

**Issue by aboutmydreams** [2d-inc/developer_quest#144]
![image](https://user-images.githubusercontent.com/34613360/61380853-b685bc00-a8dc-11e9-9bb2-4f4c16818eb5.png)

**Comment by luigi-rosso** [comment]
This is due to the new Flutter stable changing a method signature. There’s a new Flare (1.5.4) which is compatible with it. It should be as simple as changing the flare_flutter version in the pubspec.yaml. I should be able to take a look at it later today.

**Comment by aboutmydreams** [comment]
That's it. Thank you for your answer~

**Comment by pengMaster** [comment]
666

**Comment by luigi-rosso** [comment]
I just pushed a change to master that merges in the latest Flare 1.5.5.  Please make sure you are on Flutter stable.
