### ISSUE TITLE
The task tree as a package?

### ISSUE THREAD

**Issue by baumths** [2d-inc/developer_quest#157]
Hey guys! I really like the Task `Treeview` you guys built, it would be very nice if it became a package, because we don't really have a good looking treeview in flutter and the ones at [pub.dev](https://pub.dev) are very simple.

Thanks in advance!

Ps: I know I'm a little late to the party, but this would help a lot!

**Comment by luigi-rosso** [comment]
It's definitely possible to abstract this into its own thing but it would take quite a bit of work! The fundamental thing this does is the hierarchical flattening into a linear list for easy rendering in a virtualized list view.

**Comment by baumths** [comment]
I'm not a Pro in flutter, but I would gladly help to abstract it into a package!
An app I'm working on depends heavily on a good and optimized `treeview`. And the one you guys made looks incredible and very lightweight.
